language: c

before_install:
 - git submodule update --init --recursive

env:
  - LD_LIBRARY_PATH=rumpdyn/lib PATH=$PATH:rumpdyn/lib

script: BUILD_QUIET=-qq ./buildnb.sh buildrump && ./tests/test.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
