language: c

before_install:
 - git submodule update --init --recursive

env:
  - LD_LIBRARY_PATH=.:rumpdyn/lib

script: BUILD_QUIET=-qq ./buildnb.sh && ./tests/test.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
