language: c
os: linux
sudo: false

before_install:
 - git submodule update --init --recursive

matrix:
  include:
    - env: ZFS= REALCC=gcc
      compiler: gcc
    - env: ZFS=zfs  REALCC=gcc
      compiler: gcc
    - env: ZFS= REALCC=clang-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

script:
   - ( cd buildrump.sh && ./buildrump.sh -s ../src-netbsd -V MKSTATICLIB=no -qq fullbuild )
   - CC=$REALCC ./buildnb.sh -qq ${ZFS} tests ./buildrump.sh/rump

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
